version: '3'

services:
  web:
    build: ./web
    command: nodemon -L --exec yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  api:
    build: ./api
    command: nodemon -L --exec yarn start
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - /app/node_modules